version: '2'

services:

  web:
    build: .
    volumes:
      - /private/var/run/docker.sock:/var/run/docker.sock
      - ./src:/app
      - /app/var
    ports:
      - "8443:443"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - WEB_DOCUMENT_ROOT=/app/web

  mysql:
    image: mysql:5.7
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "1206:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=rocketpanel
